learning_log/learning_log/urls.py
"""
Definition of urls for learning_log.
"""

from datetime import datetime
from django.urls import path, include
from django.contrib import admin
from django.contrib.auth.views import LoginView, LogoutView

urlpatterns = [
    path('', include('learning_logs.urls',namespace='learning_logs')),
    path('admin/', admin.site.urls),
    path('users/',include('users.urls',namespace='users')),
    
]

learning_log/learning_logs/urls.py
from django.urls import path,include
from . import views
urlpatterns=[
    #主页
    path('', views.index, name='index'),
    #显示所有的主题
    path('topics/', views.topics, name='topics'),
    #特定主题的详细界面
    path('topics/<int:topic_id>/', views.topic, name='topic'),
    #用于添加新主题的网页
    path('new_topic/', views.new_topic, name='new_topic'),
    #用于添加新条目的页面
    path('new_entry/<int:topic_id>/', views.new_entry, name='new_entry'),
    #用于编辑条目的页面
    path('edict_entry/<int:entry_id>', views.edict_entry,name='edict_entry'),
    ]
app_name = 'learning_logs'

learning_log/users/urls.py
"""为应用程序users定义URL模式"""
from django.urls import path
from django.contrib.auth.views import LoginView,LogoutView

from . import views
urlpatterns=[
    #登录页面
    path('login/',LoginView.as_view(template_name='users/login.html'), name='login'),
    #注销
    path('logout/',LogoutView.as_view(next_page='/'),name='logout'),
    #
    path('register/',views.register, name='register'),
    ]
app_name='users'

learning_log/learning_logs/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Topic(models.Model):
    """用户学习的主题"""
    text=models.CharField(max_length=200)
    date_added=models.DateTimeField(auto_now_add=True)
    owner=models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        """返回模型的字符串表示"""
        return self.text

class Entry(models.Model):
    """学习到的有关某个主题的具体知识"""
    topic=models.ForeignKey(Topic,on_delete=models.CASCADE)
    text=models.TextField()
    date_added=models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural='entries'
    def __str__(self):
        return self.text[:50]+"..." 

learning_log/users/models.py
from django.db import models

# Create your models here.

learning_log/learning_logs/forms.py
from django import forms
from .models import Topic, Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model=Topic
        fields=['text']
        labels={'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model=Entry
        fields=['text']
        labels={'text': ''}
        widgets={'text':forms.Textarea(attrs={'cols':80})}

learning_log/learning_logs/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Topic, Entry
from .forms import TopicForm, EntryForm

# Create your views here.
def index(request):
    """学习笔记的主页"""
    return render(request,'learning_logs/index.html')

@login_required
def topics(request):
    """显示所有的主题"""
    topics=Topic.objects.filter(owner=request.user)
    context={'topics':topics}
    return render(request,'learning_logs/topics.html',context)

@login_required
def topic(request,topic_id):
    """显示单个主题及其所有的条目"""
    topic=Topic.objects.get(id=topic_id)
    #确认请求的主题属于当前用户
    if topic.owner !=request.user:
        raise Http404

    entries=topic.entry_set.order_by('-date_added')
    context={'topic':topic,'entries':entries}
    return render(request,'learning_logs/topic.html',context)

@login_required
def new_topic(request):
    """添加新主题"""
    if request.method !='POST':
        #未提交数据：创建一个新表单
        form=TopicForm
    else:
        #POST提交的数据，对数据进行处理
        form=TopicForm(request.POST)
        if form.is_valid():
            new_topic=form.save(commit=False)
            new_topic.owner=request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('learning_logs:topics'))

    context={'form':form}
    return render(request,'learning_logs/new_topic.html',context)

@login_required
def new_entry(request,topic_id):
    """在特定的主题中添加新条目"""
    topic=Topic.objects.get(id=topic_id)

    if request.method !='POST':
        #未提交数据，创建一个空表单
        form=EntryForm()
    else:
        #POST提交的数据，对数据进行处理
        form=EntryForm(data=request.POST)
        if form.is_valid():
            new_entry=form.save(commit=False)
            new_entry.topic=topic
            new_entry.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic_id]))
    context={'topic':topic, 'form':form}
    return render(request,'learning_logs/new_entry.html',context)

@login_required
def edict_entry(request,entry_id):
    """编辑既有条目"""
    entry=Entry.objects.get(id=entry_id)
    topic=entry.topic
    if topic.owner !=request.user:
        raise Http404
    
    if request.method !='POST':
        #初次请求，使用当前条目填充表单
        form=EntryForm(instance=entry)
    else:
        #POST提交的数据，对数据进行处理
        form=EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('learning_logs:topic',args=[topic.id]))
    
    context={'entry':entry, 'topic':topic, 'form':form}
    return render(request,'learning_logs/edict_entry.html',context)

learning_log/users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login,logout,authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def register(request):
    """注册新用户"""
    if request.method !='POST':
        #显示空的注册表单
        form=UserCreationForm()
    else:
        #处理填写好的表单
        form=UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user=form.save()
            #让用户自动登录，再重定向到主页
            authenticated_user=authenticate(username=new_user.username,password=request.POST['password1'])
            login(request,authenticated_user)
            return HttpResponseRedirect(reverse('learning_logs:index'))
    context={'form':form}
    return render(request,'users/register.html',context)

learning_log/learning_logs/templates/learning_logs/base.html
{% load bootstrap3 %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>学习笔记</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <!--静态导航栏-->
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">

            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a href="{% url 'learning_logs:index' %}" class="navbar-brand">学习笔记</a>
            </div>

            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="{% url 'learning_logs:topics' %}">主题</a> </li>             
                </ul>

                <ul class="nav navbar-nav navbar-right">
                    {% if user.is_authenticated %}
                    <li><a>Hello,{{ user.username }}.</a></li>
                    <li><a href="{% url 'users:logout' %}">注销</a></li> 
                    {% else %}
                    <li><a href="{% url 'users:register' %}">注册</a></li> 
                    <li><a href="{% url 'users:login' %}">登录</a></li>
                    {% endif %}
                </ul>
                
            </div>
        </div>
    </nav>
    
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>{% block content %}{% endblock content %}</div>
    </div> 
    
</body>
</html>

learning_log/learning_logs/templates/learning_logs/edict_entry.html
{% extends "learning_logs/base.html" %}   
{% block content %}
<head>
    <meta charset="utf-8" />
</head>
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>编辑条目:</p>
<form action="{% url 'learning_logs:edict_entry' entry.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">保存</button>
</form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/index.html
{% extends "learning_logs/base.html" %}
<head>
    <meta charset="utf-8" />
</head>
{% block header %}
<div class="jumbotron"><h1>跟踪你的学习.</h1></div>
{% endblock header %}
{% block content %}
<h2><a href="{% url 'users:register' %}">创建一个账户</a> 来制作你自己的学习笔记，并将你学习的主题罗列出来。
</h2>
<h2>每当你学习某个主题的新知识，都可以建立一个条目来总结你所学到的。</h2>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_entry.html
{% extends "learning_logs/base.html" %}
<head>
    <meta charset="utf-8" />
</head>
{% block content %}
<p><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></p>

<p>add new entry:</p>
<form action="{% url 'learning_logs:new_entry' topic.id %}" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">save changes</button>
</form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/new_topic.html
{% extends "learning_logs/base.html" %}
{% load bootstrap3 %}

{% block header %}
<p>添加新主题:</p>
{% endblock header %}

{% block content %}
<form action="{% url 'learning_logs:new_topic' %}" method="post" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
    <button name="submit" class="btn btn-primary">添加主题</button>
    {% endbuttons %}
</form>
{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topic.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h2>{{ topic }}</h2>
{% endblock header %}

{% block content %}
<p>
   <a href="{% url 'learning_logs:new_entry' topic.id %}">添加新条目</a>
</p>

   {% for entry in entries %}
    <div class="panel panel-default">
        <div class="panel-heading">
       <h3>
           {{ entry.date_added|date:'M d, Y H:i' }}
       <small>
         <a href="{% url 'learning_logs:edict_entry' entry.id %}">编辑条目</a>
       </small>
       </h3>
        </div>
    </div>
    <div class="panel-body">
        {{ entry.text|linebreaks }}
    </div>
   {% empty %}
        您还没有添加任何条目。      
   {% endfor %}

{% endblock content %}

learning_log/learning_logs/templates/learning_logs/topics.html
{% extends "learning_logs/base.html" %}

{% block header %}
<h1>主题</h1>
{% endblock header %}

{% block content %}
<ul>
    {% for topic in topics %}
    <li><h3><a href="{% url 'learning_logs:topic' topic.id %}">{{ topic }}</a></h3></li>
    {% empty %}
    <li>您还没有添加任何主题。</li>
    {% endfor %}
</ul>
<h3><a href="{% url 'learning_logs:new_topic' %}">添加新主题：</a></h3>
{% endblock content %}

learning_log/users/templates/users/login.html
{% extends "learning_logs/base.html "%}
{% load bootstrap3 %}
{% block header %}
<h2>登录你的账户</h2>
{% endblock header %}

{% block content %}



<form method="POST" action="{% url 'users:login' %}"class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

{% buttons %}
<button name="submit" class="btn btn-primary">登录</button>
{% endbuttons %}
<input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>
{% endblock content %}

learning_log/users/templates/users/register.html
{% extends "learning_logs/base.html "%}
{% load bootstrap3 %}

{% block content %}

<form method="POST" action="{% url 'users:register' %}">
    {% csrf_token %}
    {% bootstrap_form form %}
    
<button name="submit">注册</button>
<input type="hidden" name="next" value="{% url 'learning_logs:index' %}" />
</form>
{% endblock content %}